### PR TITLE
revert import * for version.py in base init file

### PR DESCRIPTION
**Pull request by bfineran**

### CODE REVIEW

**Review by Willtor — CHANGES_REQUESTED** [review]
On line 39, I think it wants to be `package_version=__version__`.

**Review by Willtor — APPROVED** [review]
Lgtm!

**Comment by bfineran** [comment]
good catch!

**Review by markurtz — APPROVED** [review]

**Comment by dhuangnm** [comment]
It looks we need this fix across all the sparse* repos?

**Comment by kazukageorge** [comment]
> It looks we need this fix across all the sparse* repos?

`__version__` gives 0.9.0 and `version` yields 0.9.0.2021XXXX. Both works fine in the api

**Pull request merged**
