### PR TITLE
[cherry-pick] Update Slack and Discourse Links (#109)

### PR DESCRIPTION
**Pull request by bfineran**

### CODE REVIEW

**Review by kevinaer — DISMISSED** [review]

**Review by mgoin — DISMISSED** [review]

**Comment by neomatrix369** [comment]
Thanks for the links, just signed up on Discourse.

Is the Slack link a public one? I couldn't sign up on it, it expects a @neuralmagic.com email address.

@jeanniefinks good work with the PRs and commits ;)

**Review by jeanniefinks — COMMENTED** [review]
@neomatrix369 
Thank you for testing. May you see if this link works better? 
https://join.slack.com/t/discuss-neuralmagic/shared_invite/zt-q1a1cnvo-YBoICSIw3L1dmQpjBeDurQ

**Comment by neomatrix369** [comment]
> @neomatrix369
> Thank you for testing. May you see if this link works better?
> https://join.slack.com/t/discuss-neuralmagic/shared_invite/zt-q1a1cnvo-YBoICSIw3L1dmQpjBeDurQ

Yes that worked perfect!
I'm on there now!

**Comment by neomatrix369** [comment]
> @neomatrix369
> Thank you for testing. May you see if this link works better?
> https://join.slack.com/t/discuss-neuralmagic/shared_invite/zt-q1a1cnvo-YBoICSIw3L1dmQpjBeDurQ

@jeanniefinks one thing to know about Slack invite links, they expire in a short while (7 days max I think) -- you may want to check where this link is generated and if you can reset this expiry setting on it

**Review by mgoin — APPROVED** [review]

**Review by jeanniefinks — APPROVED** [review]

**Pull request merged**
