### PR TITLE
Add resnet50 benchmark script

### PR DESCRIPTION
**Pull request by mgoin**

### CODE REVIEW

**Comment by mgoin** [comment]
This is the output on an AWS c5.12xlarge instance

```
python resnet50_benchmark.py 
Starting DeepSparse benchmarks using batch size 64 and 24 cores
DeepSparse Engine, Copyright 2021-present / Neuralmagic, Inc. version: 0.1.0.20210223 (f57a6c46) (release) (optimized) (system=avx512, binary=avx512)
ResNet-50 v1 Dense FP32 BenchmarkResults:
        items_per_second: 330.58802042724705
        ms_per_batch: 193.59443187713623
        batch_times_mean: 0.19359443187713624
        batch_times_median: 0.19376111030578613
        batch_times_std: 0.001058809571185983
ResNet-50 v1 Pruned Conservative FP32 BenchmarkResults:
        items_per_second: 710.0468891754213
        ms_per_batch: 90.13489246368408
        batch_times_mean: 0.09013489246368409
        batch_times_median: 0.09006881713867188
        batch_times_std: 0.000339071855544223
ResNet-50 v1 Pruned Moderate FP32 BenchmarkResults:
        items_per_second: 825.1183507288177
        ms_per_batch: 77.56463050842285
        batch_times_mean: 0.07756463050842285
        batch_times_median: 0.07747602462768555
        batch_times_std: 0.0004138887965319723
ResNet-50 v1 Pruned Moderate INT8 BenchmarkResults:
        items_per_second: 2073.438985452931
        ms_per_batch: 30.866594314575195
        batch_times_mean: 0.030866594314575196
        batch_times_median: 0.030414819717407227
        batch_times_std: 0.00112313891489126
ResNet-50 v1 Pruned Aggressive INT8 BenchmarkResults:
        items_per_second: 2325.219320470783
        ms_per_batch: 27.524285316467285
        batch_times_mean: 0.027524285316467285
        batch_times_median: 0.027516841888427734
        batch_times_std: 3.2148065922121384e-05
```

**Review by bfineran — CHANGES_REQUESTED** [review]
can we add a clear warning if VNNI is not detected

**Comment by mgoin** [comment]
New printout

```
python resnet50_benchmark.py 
Starting DeepSparse benchmarks using batch size 64 and 24 cores
Using avx512 instruction set extensions
DeepSparse Engine, Copyright 2021-present / Neuralmagic, Inc. version: 0.1.1.20210225 (1904acd2) (release) (optimized) (system=avx512, binary=avx512)
ResNet-50 v1 Dense FP32 BenchmarkResults:
        items_per_second: 328.6478744090384
        ms_per_batch: 194.73730087280273
        batch_times_mean: 0.19473730087280272
        batch_times_median: 0.19429588317871094
        batch_times_std: 0.0013594448119192202
ResNet-50 v1 Pruned Conservative FP32 BenchmarkResults:
        items_per_second: 707.832135363506
        ms_per_batch: 90.41691780090332
        batch_times_mean: 0.09041691780090332
        batch_times_median: 0.09032857418060303
        batch_times_std: 0.00035535732141432527
ResNet-50 v1 Pruned Moderate FP32 BenchmarkResults:
        items_per_second: 824.1348494592928
        ms_per_batch: 77.65719413757324
        batch_times_mean: 0.07765719413757324
        batch_times_median: 0.07759594917297363
        batch_times_std: 0.0003055320524274135
ResNet-50 v1 Pruned Moderate INT8 BenchmarkResults:
        items_per_second: 2096.742479984378
        ms_per_batch: 30.52353858947754
        batch_times_mean: 0.03052353858947754
        batch_times_median: 0.030462026596069336
        batch_times_std: 0.0003282600955974038
ResNet-50 v1 Pruned Aggressive INT8 BenchmarkResults:
        items_per_second: 2310.89339011664
        ms_per_batch: 27.69491672515869
        batch_times_mean: 0.02769491672515869
        batch_times_median: 0.027538537979125977
        batch_times_std: 0.0005905214037404011
```

**Review by bfineran — COMMENTED** [review]
@mgoin looks like the file name got slightly changed without deleting the old one

**Review by bfineran — COMMENTED** [review]
LGTM otherwise, thanks for the update

**Comment by mgoin** [comment]
> @mgoin looks like the file name got slightly changed without deleting the old one

thanks for catching that, removed

**Review by bfineran — APPROVED** [review]

**Review by markurtz — APPROVED** [review]

**Pull request merged**
