### PR TITLE
Fixing bug with prometheus metric name

### PR DESCRIPTION
**Pull request by corey-nm**
https://prometheus.io/docs/practices/naming/

hyphens are not allowed in metric names.

test plan: added regression test, tested multi model example in readme

### CODE REVIEW

**Review by bfineran — APPROVED** [review]
LGTM - one thing just cross my mind we should add is shutting down the prometheus server at the end of the unit test. I think they may be staying alive longer than the test scope

**Comment by corey-nm** [comment]
> LGTM - one thing just cross my mind we should add is shutting down the prometheus server at the end of the unit test. I think they may be staying alive longer than the test scope

It looks like its a daemon thread so I think it should be cleaned up? Do you see resources leftover?

**Comment by rahul-tuli** [comment]
> https://prometheus.io/docs/practices/naming/
> 
> Underscores are not allowed in metric names.
> 
> test plan: added regression test, tested multi model example in readme

Could we update the description, I think underscores are allowed but hyphens are not

**Comment by corey-nm** [comment]
> > https://prometheus.io/docs/practices/naming/
> > Underscores are not allowed in metric names.
> > test plan: added regression test, tested multi model example in readme
> 
> Could we update the description, I think underscores are allowed but hyphens are not

Oh yeah haha reversed it, fixed!

**Review by rahul-tuli — APPROVED** [review]
LGTM pending the description update!

**Pull request merged**
