### PR TITLE
Deprecate sockets in the API

### PR DESCRIPTION
**Pull request by Willtor**
Summary: Callers specify a core count and depend on the engine to figure out how to distribute them across sockets.

### CODE REVIEW

**Review by bnellnm — DISMISSED** [review]
accepting based on phabricator diff process

**Review by bfineran — CHANGES_REQUESTED** [review]
there's a few lines of code and docs in this repo that depend on `num_sockets`, if we're going to deprecate by raising an exception, let's definitely remove those references

**Review by tlrmchlsmth — APPROVED** [review]

**Comment by Willtor** [comment]
Hey Ben -- I did a grep for "socket" in doc and examples, and think I got everything in those directories. Are there other references I need to check?

**Review by bfineran — APPROVED** [review]
this looks good to me. Thanks Will!!
[](https://media2.giphy.com/media/Hw8vYF4DNRCKY/giphy.gif)

**Comment by Willtor** [comment]
WAAAAAAA!

tmp

**Review by tlrmchlsmth — APPROVED** [review]

**Review by tlrmchlsmth — APPROVED** [review]

**Comment by bfineran** [comment]
closing (#193)

**Pull request closed without merging**
