### PR TITLE
Reformat version.py file

### PR DESCRIPTION
**Pull request by markurtz**
- follow python conventions for __all__ exports
- relative lookup of generated-version.py

### CODE REVIEW

**Comment by bnellnm** [comment]
Thanks for fixing the path issues. Can you add an export of the splash variable as well? We need that to run dashboard benchmarks.

**Review by bnellnm — CHANGES_REQUESTED** [review]
Thanks for fixing the path issues. Can you add an export of the splash variable as well? We need that to run dashboard benchmarks.

**Comment by markurtz** [comment]
> Thanks for fixing the path issues. Can you add an export of the splash variable as well? We need that to run dashboard benchmarks.

@bnellnm added, let me know if that looks good

**Review by bnellnm — APPROVED** [review]
Looks good.  Thanks Mark

**Review by mgoin — APPROVED** [review]

**Pull request merged**
