### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by jeanniefinks**
Technical content needed specifically for

README.md
CONTRIBUTING.md
DEVELOPING.md

### CODE REVIEW

**Review by mgoin — DISMISSED** [review]
Thanks Jeannie, great changes. I can fill in a lot of the engineering sections so I think this is good to land.

A lot has changed/been renamed so merging might be a bit hairy, especially in setup.py

**Review by bnellnm — CHANGES_REQUESTED** [review]
Looks good overall.  Just a few minor comments/corrections.

**Review by mgoin — DISMISSED** [review]

**Review by mgoin — APPROVED** [review]
LGTM

**Review by bnellnm — APPROVED** [review]
LGTM.  Thanks Jeannie.  I think the setup.py keywords are still missing "sparse".  Can you add that before you merge?

**Pull request merged**
