### PR TITLE
Performance Analysis

### PR DESCRIPTION
**Pull request by rahul-tuli**
This PR represents the first feature branch for 
building out the performance analysis module

Performance Analysis Module: would serve as a utility for prospective users
who want to test DeepSparse Performance Speedups on
local onnx models, to assess if DeepSparse is a viable
runtime candidate before they spend more resources on
sparsification of the model.

PR Component:
- [X] deepsparse.performance_analysis.model_analysis

Exposes SparseZoo Model Analysis as a DeepSparse CLI utility

```bash
~ deepsparse.performance_analysis.model_analysis --help
usage: deepsparse.performance_analysis.model_analysis [-h] [--outfile OUTFILE]
                                                      model_path

SparseZoo Model Analysis utility for ONNX models

positional arguments:
  model_path         Path to a local ONNX model or SparseZoo model stub like zoo:cv/c
                     lassification/resnet_v1-50/pytorch/sparseml/imagenet/pruned-
                     moderate

optional arguments:
  -h, --help         show this help message and exit
  --outfile OUTFILE  If specified model analysis results will be written to this file
```

The help message in this command will be updated on SparseZoo side.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1203627690604301

### CODE REVIEW

**Review by corey-nm — APPROVED** [review]
lgtm, easy review

**Review by bfineran — CHANGES_REQUESTED** [review]
Why are we pointing to a sparsezoo cli here? The deepsparse cli will be for performance analysis. The one implemented in sparsezoo is for general model analysis

**Comment by rahul-tuli** [comment]
> lgtm, easy review



> Why are we pointing to a sparsezoo cli here? The deepsparse cli will be for performance analysis. The one implemented in sparsezoo is for general model analysis

This was a requirement from product docs; but requirements have since been updated and this is no longer needed now; Closing out this PR 🔥

**Comment by rahul-tuli** [comment]
> lgtm, easy review

Thanks for the quick review here though!

**Pull request closed without merging**
