### PR TITLE
Fix documentation about TextGeneration

### PR DESCRIPTION
**Pull request by luis5tb**
TextGeneration takes model_path as parameter instead of model

### CODE REVIEW

**Comment by mgoin** [comment]
> TextGeneration takes model_path as parameter instead of model

Hey @luis5tb `model=` should work for nightly and/or the upcoming 1.7, are you using the 1.6 release possibly?

**Comment by luis5tb** [comment]
> > TextGeneration takes model_path as parameter instead of model
> 
> Hey @luis5tb `model=` should work for nightly and/or the upcoming 1.7, are you using the 1.6 release possibly?

Yep using 1.6.1, following that documentation I hit it and saw that it was solved by adding model_path. Perhaps the code should take both then to keep backwards compatibility or add a note in the docs

**Comment by luis5tb** [comment]
Should I close this then?

**Comment by mgoin** [comment]
@luis5tb the nightly should both accept `model_path` and `model`, we just added `model` as a new alias that we'll be using going forward so backwards compatibility is good. it didn't make it into 1.6.1 though

**Pull request closed without merging**
